version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "6500:6500"
    environment:
      - DB_HOST=localhost
      - DB_USER=portal_user
      - DB_PASSWORD=PyfybzPyfybz89
      - DB_NAME=knowledge_portal
      - JWT_SECRET=placeholder
    # depends_on:
    #   - db
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    ports:
      - "3001:3001"
    environment:
      - REACT_APP_API_URL=http://localhost:6500
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

  # db:
  #   image: mariadb:10.11
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=<fhvfktq12
  #     - MYSQL_DATABASE=knowledge_portal
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - db_data:/var/lib/mysql
  #     - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
